name: Lint

on: [push, pull_request]

jobs:
  JS-Lint:
    runs-on: ubuntu-16.04
    if: startsWith( github.repository, 'elementor/' )
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Check JS files diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/*.+(js|ts|json|jsx|tsx)
      - name: Cache node modules
        if: ${{ env.GIT_DIFF }}
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: ${{ env.GIT_DIFF }}
        run: npm i
      - name: Run Lint
        if: ${{ env.GIT_DIFF }}
        run: ./node_modules/eslint/bin/eslint.js ${{ env.GIT_DIFF }}

  PHP-Lint:
    runs-on: ubuntu-16.04
    if: startsWith( github.repository, 'elementor/' )
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Check PHP files diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/*.php
      - name: Setup PHP 7.4
        if: ${{ env.GIT_DIFF }}
        uses: shivammathur/setup-php@9882bed06691b3a085010c1602ce43ef18f15c5b # v2
        with:
          php-version: '7.4'
      - name: Install Dependencies
        if: ${{ env.GIT_DIFF }}
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          composer global require wp-coding-standards/wpcs
          composer require php-parallel-lint/php-parallel-lint
      - name: Run Lint
        if: ${{ env.GIT_DIFF }}
        run: |
          export PATH=$HOME/.composer/vendor/bin:$PATH
          phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
          phpcs -p -s -n ${{ env.GIT_DIFF }} --standard=./ruleset.xml --extensions=php
      - name: Run PHP Syntax Lint
        if: ${{ env.GIT_DIFF }}
        run: |
          export PATH=$HOME/.composer/vendor/bin:$PATH
          php5.6 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor ${{ env.GIT_DIFF }}
          php7.0 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor ${{ env.GIT_DIFF }}
          php7.1 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor ${{ env.GIT_DIFF }}
          php7.2 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor ${{ env.GIT_DIFF }}
          php7.3 vendor/bin/parallel-lint --blame --exclude node_modules --exclude vendor ${{ env.GIT_DIFF }}
