name: PHPUnit

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        wordpress_versions: ['latest', '5.5', '5.4', '5.3']
    name: WordPress ${{ matrix.wordpress_versions }}
    steps:
      - name: Startup MySQL service
        run: sudo /etc/init.d/mysql start
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          bash bin/install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wordpress_versions }}
          wget --quiet -O /tmp/phpunit-5 https://phar.phpunit.de/phpunit-5.phar
          wget --quiet -O /tmp/phpunit-6 https://phar.phpunit.de/phpunit-6.phar
          wget --quiet -O /tmp/phpunit-7 https://phar.phpunit.de/phpunit-7.phar
          composer install
      - name: PHP5.6
        run: php5.6 /tmp/phpunit-5
      - name: PHP5.6 - Multisite
        run: WP_MULTISITE=1 php5.6 /tmp/phpunit-5
      - name: PHP7.0
        run: php7.0 /tmp/phpunit-6
      - name: PHP7.0 - Multisite
        run: WP_MULTISITE=1 php7.0 /tmp/phpunit-6
      - name: PHP7.1
        run: php7.1 /tmp/phpunit-6
      - name: PHP7.1 - Multisite
        run: WP_MULTISITE=1 php7.1 /tmp/phpunit-6
      - name: PHP7.2
        run: php7.2 /tmp/phpunit-6
      - name: PHP7.2 - Multisite
        run: WP_MULTISITE=1 php7.2 /tmp/phpunit-6
      - name: PHP7.3
        run: php7.3 /tmp/phpunit-6
      - name: PHP7.3 - Multisite
        run: WP_MULTISITE=1 php7.3 /tmp/phpunit-6
      - name: PHP7.4
        run: php7.4 /tmp/phpunit-7
      - name: PHP7.4 - Multisite
        run: WP_MULTISITE=1 php7.4 /tmp/phpunit-7
